// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WailletAPI.Data;

#nullable disable

namespace WailletAPI.Migrations
{
    [DbContext(typeof(WailletDbContext))]
    partial class WailletDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WailletAPI.Models.Account", b =>
                {
                    b.Property<long>("AccKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("acc_key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccKey"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(19,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("CryptoFlag")
                        .HasColumnType("bit")
                        .HasColumnName("crypto_flag");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("currency_code");

                    b.Property<long>("UserKey")
                        .HasColumnType("bigint")
                        .HasColumnName("user_key");

                    b.HasKey("AccKey");

                    b.HasIndex("UserKey")
                        .IsUnique()
                        .HasFilter("crypto_flag = 0");

                    b.HasIndex("UserKey", "CurrencyCode")
                        .IsUnique()
                        .HasFilter("crypto_flag = 1");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WailletAPI.Models.CryptoCurrency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("CryptoCurrencies");

                    b.HasData(
                        new
                        {
                            Code = "BTC",
                            Name = "Bitcoin"
                        },
                        new
                        {
                            Code = "ETH",
                            Name = "Ethereum"
                        },
                        new
                        {
                            Code = "LTC",
                            Name = "Litecoin"
                        });
                });

            modelBuilder.Entity("WailletAPI.Models.User", b =>
                {
                    b.Property<long>("UserKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserKey"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserKey");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WailletAPI.Models.Account", b =>
                {
                    b.HasOne("WailletAPI.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WailletAPI.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
